export const CONSTANT = /\bsabet\b/g;
export const INT = /\brakam\b/g;
export const FLOAT = /\b3ayem\b/g;
export const STRING = /\bgomla\b/g;
export const INTVALUE = /[0-9]+/g;
export const FLOATVALUE1 = /[+-]?\d+(\.\d+)?$/g
export const STRINGVALUE = /".*"/g;
export const CHAR = /\b7arf\b/g;
export const BOOL = /\bbool\b/g;
export const IF = /\blaw\b/g;
export const ELSE = /\blaken\b/g;
export const WHILE = /\btalama\b/g;
export const DO = /\be3mel\b/g;
export const SWITCH = /\bbadel\b/g;
export const CASE = /\b7alet\b/g;
export const DEFAULT = /\bel3ady\b/g;
export const FOR = /\blef\b/g;
export const BREAK = /\bbreak\b/g;
export const RETURN = /return/g;
export const VOID = /\bvoid\b/g;
export const CHARVALUE = / \'[a-zA-Z0-9]\'/g
export const COMMENT = /(\/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+\/)|(\/\/.*)/g
export const IDENTIFIER  = /[a-zA-Z][_a-zA-Z0-9]*/g;
export const ERROR_IDENTIFIER = /\b([0-9]+[a-zA-Z]+)\b/g
// export const ERROR_FLOAT_WORDS = /(([0-9]+)(\.[0-9]+)([a-zA-Z0-9]+))/g;
export const ERROR_WORDS_DOT = /([a-zA-Z][_a-zA-Z0-9]*\.[_a-zA-Z0-9]*)/g; 
